let users = JSON.parse(localStorage.getItem("inventoryUsers")) || [ { id: 1, name: "Administrator", username: "admin", password: "admin123", role: "Admin" } ]; 
let inventory = JSON.parse( localStorage.getItem("inventoryData") ) || [ { id: 1, name: "Rice", category: "Grocery", price: 55, quantity: 20 }, { id: 2, name: "Cooking Oil", category: "Grocery", price: 85, quantity: 15 }, { id: 3, name: "Soap", category: "Personal Care", price: 35, quantity: 5 } ];
function saveData() { localStorage.setItem( "inventoryUsers", JSON.stringify(users) ); localStorage.setItem( "inventoryData", JSON.stringify(inventory) ); }  document.addEventListener("DOMContentLoaded", function () { checkLogin(); displayInventory(); displayUsers(); updateDashboard(); }); 
function checkLogin() { const loggedInUser = localStorage.getItem("loggedInUser"); if (loggedInUser) { const user = JSON.parse(loggedInUser); showMainSystem(user); } else { showLogin(); } }   
function showLogin() { document.getElementById("loginPage").style.display = "flex"; document.getElementById("registerPage").style.display = "none"; document.getElementById("mainSystem").style.display = "none"; } 
function showRegister() { document.getElementById("loginPage").style.display = "none"; document.getElementById("registerPage").style.display = "flex"; document.getElementById("mainSystem").style.display = "none"; document.getElementById("registerForm").reset(); document.getElementById("registerMessage").innerHTML = ""; } document.getElementById("loginForm").addEventListener( "submit", function (event) { event.preventDefault(); const username = document.getElementById("loginUsername").value.trim(); const password = document.getElementById("loginPassword").value; const user = users.find(function (u) { return ( u.username === username && u.password === password ); }); if (user) { localStorage.setItem( "loggedInUser", JSON.stringify(user) ); document.getElementById( "loginMessage" ).innerHTML = ""; showMainSystem(user); document.getElementById( "loginForm" ).reset(); } else { document.getElementById( "loginMessage" ).innerHTML = ` <div class="alert alert-danger mt-3"> ❌ Invalid username or password. </div> `; } } ); document.getElementById("registerForm").addEventListener( "submit", function (event) { event.preventDefault(); const name = document.getElementById("registerName").value.trim(); const username = document.getElementById( "registerUsername" ).value.trim(); const password = document.getElementById( "registerPassword" ).value; const existingUser = users.find(function (u) { return u.username === username; }); if (existingUser) { document.getElementById( "registerMessage" ).innerHTML = ` <div class="alert alert-danger mt-3"> ❌ Username already exists. </div> `; return; }  const newUser = { id: Date.now(), name: name, username: username, password: password, role: "Admin" }; users.push(newUser); saveData(); document.getElementById( "registerMessage" ).innerHTML = ` <div class="alert alert-success mt-3"> ✅ Account created successfully! You can now login. </div> `; document.getElementById( "registerForm" ).reset(); } );  
function showMainSystem(user) { document.getElementById("loginPage").style.display = "none"; document.getElementById("registerPage").style.display = "none"; document.getElementById("mainSystem").style.display = "block"; document.getElementById( "welcomeUser" ).textContent = "Welcome, " + user.name; displayInventory(); displayUsers(); updateDashboard(); }  
function logout() { const confirmLogout = confirm("Are you sure you want to logout?"); if (confirmLogout) { localStorage.removeItem("loggedInUser"); showLogin(); } }  
function showSection(sectionId) { const sections = document.querySelectorAll(".system-section"); sections.forEach(function (section) { section.style.display = "none"; }); document.getElementById(sectionId).style.display = "block"; window.scrollTo({ top: 0, behavior: "smooth" }); }  
function displayInventory(data = inventory) { const tableBody = document.getElementById( "inventoryTableBody" ); const emptyMessage = document.getElementById( "emptyInventory" ); tableBody.innerHTML = ""; if (data.length === 0) { emptyMessage.style.display = "block"; return; } emptyMessage.style.display = "none"; data.forEach(function (product) { let status; let statusClass; if (product.quantity === 0) { status = "Out of Stock"; statusClass = "stock-out"; } else if (product.quantity <= 5) { status = "Low Stock"; statusClass = "stock-low"; } else { status = "In Stock"; statusClass = "stock-good"; } const row = document.createElement("tr"); row.innerHTML = ` <td>${product.id}</td> <td> <strong>${escapeHTML(product.name)}</strong> </td> <td> ${escapeHTML(product.category)} </td> <td> ₱${Number(product.price).toFixed(2)} </td> <td> ${product.quantity} </td> <td> <span class="${statusClass}"> ${status} </span> </td> <td> <button class="action-btn edit-btn" onclick="editProduct(${product.id})" > ✏️ Edit </button> <button class="action-btn delete-btn" onclick="deleteProduct(${product.id})" > 🗑️ Delete </button> </td> `; tableBody.appendChild(row); }); }  function openAddModal() { document.getElementById( "modalTitle" ).textContent = "Add Product"; document.getElementById( "productForm" ).reset(); document.getElementById( "productId" ).value = ""; const modal = new bootstrap.Modal( document.getElementById("productModal") ); modal.show(); }  document.getElementById("productForm").addEventListener( "submit", function (event) { event.preventDefault(); const id = document.getElementById( "productId" ).value; const name = document.getElementById( "productName" ).value.trim(); const category = document.getElementById( "productCategory" ).value.trim(); const price = parseFloat( document.getElementById( "productPrice" ).value ); const quantity = parseInt( document.getElementById( "productQuantity" ).value ); if (id) { const product = inventory.find( p => p.id === Number(id) ); if (product) { product.name = name; product.category = category; product.price = price; product.quantity = quantity; } } /* CREATE */ else { const newProduct = { id: Date.now(), name: name, category: category, price: price, quantity: quantity }; inventory.push(newProduct); } saveData(); displayInventory(); updateDashboard(); const modal = bootstrap.Modal.getInstance( document.getElementById( "productModal" ) ); modal.hide(); } ); 
function editProduct(id) { const product = inventory.find( p => p.id === id ); if (!product) return; document.getElementById( "modalTitle" ).textContent = "Edit Product"; document.getElementById( "productId" ).value = product.id; document.getElementById( "productName" ).value = product.name; document.getElementById( "productCategory" ).value = product.category; document.getElementById( "productPrice" ).value = product.price; document.getElementById( "productQuantity" ).value = product.quantity; const modal = new bootstrap.Modal( document.getElementById( "productModal" ) ); modal.show(); } 
function deleteProduct(id) { const product = inventory.find( p => p.id === id ); if (!product) return; const confirmDelete = confirm( `Delete "${product.name}" from inventory?` ); if (confirmDelete) { inventory = inventory.filter( p => p.id !== id ); saveData(); displayInventory(); updateDashboard(); } } 
function searchInventory() { const search = document.getElementById( "searchInput" ).value .toLowerCase() .trim(); const filtered = inventory.filter(function (product) { return ( product.name .toLowerCase() .includes(search) || product.category .toLowerCase() .includes(search) || String(product.id) .includes(search) ); }); displayInventory(filtered); } 
function clearSearch() { document.getElementById( "searchInput" ).value = ""; displayInventory(); } 
function updateDashboard() {  document.getElementById( "totalProducts" ).textContent = inventory.length;  const totalStock = inventory.reduce( function (total, product) { return total + product.quantity; }, 0 ); document.getElementById( "totalStock" ).textContent = totalStock; const lowStock = inventory.filter( product => product.quantity > 0 && product.quantity <= 5 ).length; document.getElementById( "lowStock" ).textContent = lowStock;  document.getElementById( "totalUsers" ).textContent = users.length; } 
function displayUsers() { const tableBody = document.getElementById( "usersTableBody" ); if (!tableBody) return; tableBody.innerHTML = ""; users.forEach(function (user, index) { const row = document.createElement("tr"); row.innerHTML = ` <td> ${index + 1} </td> <td> ${escapeHTML(user.name)} </td> <td> ${escapeHTML(user.username)} </td> <td> <span class="badge bg-primary"> ${user.role} </span> </td> <td> ${ user.username !== "admin" ? ` <button class="action-btn delete-btn" onclick="deleteUser(${user.id})" > 🗑️ Delete </button> ` : ` <span class="text-muted"> Main Admin </span> ` } </td> `; tableBody.appendChild(row); }); }  function deleteUser(id) { const user = users.find( u => u.id === id ); if (!user) return; const confirmDelete = confirm( `Delete user "${user.username}"?` ); if (confirmDelete) { users = users.filter( u => u.id !== id ); saveData(); displayUsers(); updateDashboard(); } }  
function escapeHTML(text) { const div = document.createElement("div"); div.textContent = text; return div.innerHTML; 
} 

